min_vel_xy: 0.013
min_vel_yaw: 0.02
goal_x: 0.25  # meters ahead of tag
goal_yaw: 0.0  # radians relative to tag frame
error_threshold_xy: 0.01
error_threshold_yaw: 0.005
timeout_xy: 500
timeout_yaw: 500

pid_x: { p: 0.2, i:  0.01, d: 0.0, i_clamp_max:  1.0, i_clamp_min: -1.0, antiwindup: false, publish_state: false }
pid_y: { p: 0.2, i:  0.01, d: 0.0, i_clamp_max:  1.0, i_clamp_min: -1.0, antiwindup: false, publish_state: false }
pid_yaw: { p: 0.5, i:  0.02, d: 0.0, i_clamp_max:  1.0, i_clamp_min: -1.0, antiwindup: false, publish_state: false }

#export ROS_HOSTNAME=10.12.172.181
