global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 1.0
transform_tolerance: 0.5
static_map: true
track_unknown_space: true
resolution: 2.0
width: 50
height: 50

plugins:
  - { name: static,                  type: "costmap_2d::StaticLayer" }
#  - { name: inflation_global,                 type: "costmap_2d::InflationLayer" }
