global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 1.0
transform_tolerance: 0.5
static_map: true
track_unknown_space: true
resolution: 0.05
width: 500
height: 500

plugins:
  - { name: static,                  type: "costmap_2d::StaticLayer" }
